### ISSUE TITLE
Ferrum::DeadBrowserError Errors raised on Heroku

### ISSUE THREAD

**Issue by sulleh** [rubycdp/ferrum#103]
I mentioned this in #96 , but after successfully having Ferrum running within my application on Heroku, I have recently seen all of my Ferrum workers start to error out and throw the error `Ferrum::DeadBrowserError` 

 I'm using the [Heroku Chrome Buildpack](https://elements.heroku.com/buildpacks/heroku/heroku-buildpack-google-chrome) with the Chrome version of `84.0.4147.105` and the Rails version of 5.1.7.

When I run this locally everything works as expected, and I don't believe there's been any changes to my code (since the error is generated before we even really hit my code) 

Steps to reproduce:

Open up a Rails Console
`heroku run rails console` 

Create a browser instance 
`client = Ferrum::Browser.new` 

Go to a website 
`client.goto("http://yahoo.com")` 

get the error `Ferrum::DeadBrowserError`

**Comment by sulleh** [comment]
I should also mention that if I run this locally on my Mac (with the same version of Google Chrome) Ferrum works as expected.

**Comment by route** [comment]
Like I said I need you to turn on debug mode and attach log, I can do nothing without it. Most likely it’s not ferrum issue

**Comment by sulleh** [comment]
[ferrum_dead_browser.log](https://github.com/rubycdp/ferrum/files/5001622/ferrum_dead_browser.log)

here are the logs pulled from job running in sidekiq - I can reproduce the same error in the Rails console with the steps I indicated above.

**Comment by balt5r** [comment]
Linked #129. On Digital Ocean.

@sulleh did you find a solution?

**Comment by sulleh** [comment]
I do think was a RAM issue.  Upgrading the RAM resolved the issue (or upgrading the version of Chrome - hard to tell the difference between the two :)

**Comment by route** [comment]
Yea I see that after `goto` call log suddenly stops, so I guess it was a RAM issue. @sulleh sorry it took me so long to answer. I think it can be closed now.

**Comment by Nakilon** [comment]
> I do think was a RAM issue. Upgrading the RAM resolved the issue (or upgrading the version of Chrome - hard to tell the difference between the two :)

How much did you RAM?
I've got a docker log from my scraper that looks like
```none
...
Ferrum::PendingConnectionsError
Timed out waiting for response.
Timed out waiting for response.
...
Browser is dead or given window is closed (Ferrum::DeadBrowserError)
can't create Thread: Resource temporarily unavailable (ThreadError)
can't create Thread: Resource temporarily unavailable (ThreadError)
...
Browser did not produce websocket url within 10 seconds
Browser did not produce websocket url within 10 seconds
...
ThreadError: can't create Thread: Resource temporarily unavailable\n\t/usr/local/bundle/gems/webrick-1.8.1/lib/webrick/server.rb:289:in `start'
ThreadError: can't create Thread: Resource temporarily unavailable\n\t/usr/local/bundle/gems/webrick-1.8.1/lib/webrick/server.rb:289:in `start'
...
```
and now a ton of zombie chrome processes.

**Comment by Nakilon** [comment]
This is interesting: https://github.com/rubycdp/ferrum/blob/ec6d9e5eee66a30b93509ef6a6bee359b84dc295/lib/ferrum/browser.rb#L239-L243

The `process.stop` in not insured if `client.close` failed. I don't see the "quit" in my backtraces log but nevertheless.

**Comment by Nakilon** [comment]
Meh, even with this 
```diff
diff --git a/scrapper/scraper/app.rb b/scrapper/scraper/app.rb
index ceb3973..5eee0e6 100644
--- a/scrapper/scraper/app.rb
+++ b/scrapper/scraper/app.rb
@@ -54,7 +54,13 @@ module Scraper
         "jpg"
       ]
     ensure
+      pid = browser.process.pid
+      begin
       browser&.quit
+      ensure
+      browser.process&.stop
+      Process.kill "TERM", pid rescue Errno::ESRCH
+      end
     end
   end
```
`$ docker exec scraper ps aux | grep chrome | wc` is still leaking
