### ISSUE TITLE
Install Chromium binary as Puppeteer it does

### ISSUE THREAD

**Issue by AlexWayfer** [rubycdp/ferrum#105]
https://github.com/puppeteer/puppeteer/blob/4ee4649/README.md#installation

> Note: When you install Puppeteer, it downloads a recent version of Chromium (~170MB Mac, ~282MB Linux, ~280MB Win) that is guaranteed to work with the API. To skip the download, or to download a different browser, see Environment variables.

I think it makes things easier.

Also, I don't want to download trunk version and I didn't find stable one at the link from this project README, https://www.chromium.org/getting-involved/download-chromium

**Comment by route** [comment]
@AlexWayfer does https://download-chromium.appspot.com/ show correct browser for your OS? You don't need to download Chromium, Chrome should also work if you have it installed.

I didn't want to overcomplicate things with downloading a browser like Puppeteer does, I don't like this approach. You can also set env vars or even do it in the code to setup correct path to the browser for Ferrum, how you get the browser is part of the provisioning of your system.

**Comment by AlexWayfer** [comment]
> @AlexWayfer does https://download-chromium.appspot.com/ show correct browser for your OS?

Doesn't matter, there is unstable build:

> This is a raw build of Chromium for Linux x64, right off the trunk. It may be tremendously buggy.

![image](https://user-images.githubusercontent.com/6510020/90426901-750ca500-e0ca-11ea-8c4a-5b235fd7885b.png)

I don't want to use unstable browser in my code.

> how you get the browser is part of the provisioning of your system not part of installing a gem.

I think, if a gem requires a browser (can't work without it) — it's a part of the gem too.

Sadly, but as you wish.

**Comment by route** [comment]
There are many libs around with this philosophy minimagick is only one of them it expects mogrify command to be in PATH. Ferrum doesn't have to use bleeding edge Chromium, don't you have stable Chrome installed?

**Comment by AlexWayfer** [comment]
> Ferrum doesn't have to use bleeding edge Chromium, don't you have stable Chrome installed?

I have, but some collaborators can be against installed Chrome (or Chromium) on their computers, or, more important, it can be harder to use in CI. Oh, though it can be installed as package for specific CI's image via standard commands… OK, I think it's not critical, it'd be just simpler. But… also now I'm understanding that library which installing "the latest available Chromium" locally and uses it — this version of Chromium will be stuck, so after a year of package installation you will use old Chromium even if there is fresh version on your computer. OK. Thank you for responses. I just wanted to clarify, discuss, consider both options.

**Comment by route** [comment]
Goog goog, yes I still think it's overkill. Thanks
