### ISSUE TITLE
Add `go_to` alias for `goto`

### ISSUE THREAD

**Issue by AlexWayfer** [rubycdp/ferrum#106]
I don't know why there is `goto`. I didn't find such method in [the official documentation](https://chromedevtools.github.io/devtools-protocol/). But there are two words, and I think we should use underscore. For backward compatibility, I suggest not to rename, but add the alias. What do you think?

**Comment by AlexWayfer** [comment]
> Sounds good!

OK, then I'm going to create a PR>

**Comment by AlexWayfer** [comment]
But at first I want to done some documentation and formatting issues, like #107, #108, #108 + unready RuboCop addition.

**Comment by AlexWayfer** [comment]
> But at first I want to done some documentation and formatting issues, like #107, #108, #108 + unready RuboCop addition.

Mentioned PRs are merged (thank you), now there is #110 for "RuboCop addition". Pretty doubtful, but I think useful.

**Comment by AlexWayfer** [comment]
Is it can be closed or maybe we want to deprecate `goto` method?

PR was merged.

/cc @alexanderadam

**Comment by AlexWayfer** [comment]
When we can expect a new release with this?

**Comment by route** [comment]
I need to work on a few more features and then will release new version

**Comment by trkoch** [comment]
`README` already suggests `go_to` since it's in master. Just wanted to mention I was tricked by this.
