### ISSUE TITLE
Why does it return Ferrum::CyclicObject?

### ISSUE THREAD

**Issue by Nakilon** [rubycdp/ferrum#112]
```
br = Ferrum::Browser.new
br.goto "https://google.com"

br.evaluate "( function(node){ return {a: 1, b: 2} } )(arguments[0])", br.at_css("div")
#=> {"a"=>1, "b"=>2}
br.evaluate "( function(node){ return {a: node, b: node} } )(arguments[0])", br.at_css("div")
#=> #<Ferrum::CyclicObject JavaScript object that cannot be represented in Ruby>
br.evaluate "( function(node){ return [node, node] } )(arguments[0])", br.at_css("div")
#=> [#<Ferrum::Node @target_id="E9B599ACCDC0B7F5DC344C424296C6C0" @node_id=10 @description={"nodeId"=>0, "backendNodeId"=>59, "nodeType"=>1, "nodeName"=>"DIV", "localName"=>"div", "nodeValue"=>"", "childNodeCount"=>2, "attributes"=>[]}>, #<Ferrum::Node @target_id="E9B599ACCDC0B7F5DC344C424296C6C0" @node_id=10 @description={"nodeId"=>0, "backendNodeId"=>59, "nodeType"=>1, "nodeName"=>"DIV", "localName"=>"div", "nodeValue"=>"", "childNodeCount"=>2, "attributes"=>[]}>]
```

**Comment by alexanderadam** [comment]
Interesting. I would love to know the same.
Can you explain your bugfix a bit?

**Comment by Nakilon** [comment]
@alexanderadam oh, it was a while ago. IIRC the bug is in the `seen` memoization.  
It does not pop values from it when backtracking through the `{}` tree. And in case of `[]` another code is used that does not have this `seen` and exception thing.

**Comment by Nakilon** [comment]
It's impossible to debug when it's in Ruby level so as you can see, later I tried two other implementations of "circular object detection" on the JS level. And in the end just replaced it all with `return false`, heh. https://github.com/Nakilon/ferrum/commit/7ded10ea382db6f4d6dfcdb973b668fbe5581dd7

**Comment by alexanderadam** [comment]
@route what are your thoughts on that?

**Comment by anle1337** [comment]
I'm also getting this message when i run a brower.css(".some-class"). Why? This is a big blocker, basically making this gem unusable

**Comment by Nakilon** [comment]
> I'm also getting this message when i run a brower.css(".some-class"). Why? This is a big blocker, basically making this gem unusable

IIRC it parses your node and if there is something complex in it, like JS or JS events attached, then it can cause this. In my case it failed on the Google Search webpage because there is some JS framework for event used there... I don't remember details.

**Comment by anle1337** [comment]
Thanks, it is practically too dangerous to use with these errors on a production app. I opted for selenium-webdriver gem + chromedriver to solve my problems

**Comment by quesurifn** [comment]
@anle1337 you can use this: 

`gem 'ferrum',  git: 'https://github.com/quesurifn/ferrum'`

OR 

`gem 'ferrum',  git: 'https://github.com/Nakilon/ferrum`

to implement the fix. 

I was able to get it to work after this.

**Comment by anle1337** [comment]
> @anle1337 you can use this:
> 
> `gem 'ferrum', git: 'https://github.com/quesurifn/ferrum'`
> 
> OR
> 
> `gem 'ferrum', git: 'https://github.com/Nakilon/ferrum`
> 
> to implement the fix.
> 
> I was able to get it to work after this.

Thanks

**Comment by balt5r** [comment]
+1

**Comment by AlexWayfer** [comment]
> +1

https://github.com/ruby-i18n/i18n/pull/424#issuecomment-429554568

**Comment by route** [comment]
Looks good to me, on the first glance. Sorry to make you wait for so long. Life happened :)

**Comment by balt5r** [comment]
> > +1
> 
> [ruby-i18n/i18n#424 (comment)](https://github.com/ruby-i18n/i18n/pull/424#issuecomment-429554568)

+1
