### ISSUE TITLE
Proper way to ensure that the page is loaded and ready to work with?

### ISSUE THREAD

**Issue by Nakilon** [rubycdp/ferrum#114]
```
require "ferrum"

br = Ferrum::Browser.new headless: false
br.goto "https://google.com/"
br.at_css("input[type=text]").focus.type "Ruby", :enter
sleep 2
br.at_css("body")
```
If I decrease `sleep` to `1` or remove the line at all it throws:
```
ferrum-0.9/lib/ferrum/browser/client.rb:46:in `command': Timed out waiting for response. It's possible that this happened because something took a very long time (for example a page load was slow). If so, setting the :timeout option to a higher value might help. (Ferrum::TimeoutError)
```
`br.network.wait_for_idle` hangs in the same way.
And this too:
```
t = Time.now
begin
  br.network.wait_for_idle timeout: 1
rescue Ferrum::TimeoutError
  raise if Time.now > t + 10
  retry
end
```

**Comment by route** [comment]
I'm afraid there's no such way currently in Ferrum, it's all done in Cuprite and Capybara raising errors. Thanks for working example, I'll try to think what to do with it

**Comment by Nakilon** [comment]
Just saying that if I was currently working in test automation and wanted to try Ferrum instead of Selenium this would be the reason to discard the idea. Because Selenium does not have such issue that "if some page for any random reason loads longer than usual and you didn't put a `sleep` the whole program will hang" that what was happening here in the loop example as I remember -- no matter if it's `wait_for_idle` or node lookup, if it was called before the full page load you are stuck.

**Comment by route** [comment]
@Nakilon Well you cannot use `Ferrum` instead of `Selenuim`, `Ferrum` is like `Puppeteer` in JS which is not for test automation you should use https://github.com/rubycdp/cuprite for tests in Ruby.

**Comment by Nakilon** [comment]
Isn't Cuprite analogue to Capybara while Ferrum is analogue to Selenium-Webdriver?

**Comment by route** [comment]
Ferrum is for browser automation, it's not for tests. It doesn't handle elements disappearing or content assertions. Cuprite is a driver for Capybara not a replacement for it and there's no such thing as Webdriver for Cuprite/Ferrum because they simple don't use it.

**Comment by nurettin** [comment]
[Watir](https://www.rubydoc.info/gems/watir/Watir/Wait) uses a technique where it waits for the element to exist in dom, I guess we can use this sort of waiting to make sure the element has been rendered into the DOM before proceeding.

**Comment by route** [comment]
@Nakilon in your case a proper code would look like:

```ruby
browser = Ferrum::Browser.new
browser.go_to("https://google.com/")
browser.at_css("input[type=text]").focus.type("Ruby", :enter)
browser.wait_for_reload(2) # here you can set even 100
browser.at_css("body")
```

Some explanation here, `wait_for_idle` is for purpose of waiting of AJAX requests, which is not the case for you. Sleep will work though if you don't know for how long it would take for page to reload you either wait for too long or it's not enough and error is happening. So in other words if you know for sure the reload of the whole page would happen, use `wait_for_reload` with max amount of time you are ready to wait until give up, it's safe to set it to high values because it will return sooner immediately after page is reloaded. I'll keep the ticket open for now as I want to fix some related to it stuff.

**Comment by ttilberg** [comment]
@route I notice the PR is titled `DOM methods should not be async`. Can you give a short description of what was happening, and how it affects this issue? I'm having a hard time reconciling it, while at the same time feeling like I can almost understand. Just hoping to follow along.

**Comment by route** [comment]
@ttilberg sure, so in this script that author provided we call at_css but internally it used evaluate_async with promise and timeout, so even though node doesn’t exist on a page we still waited for timeout to happen and reject promise, only then returning with timeout error. Now if node doesn’t exist it returns immediately with error. It’s not directly related to the issue but this unwanted timeout should have been fixed.

**Comment by Nakilon** [comment]
For those who hit this thread.  
Current error message in this case is:
```
Could not find node with given id (Ferrum::NodeNotFoundError)
```
