### ISSUE TITLE
Way to move the browser window?

### ISSUE THREAD

**Issue by Nakilon** [rubycdp/ferrum#115]
When running Capybara on macOS with external display attached I made it move the browser window to external display automatically because initially it opens it on the same display with Terminal. The last line was like this:
```ruby
browser.manage.window.position = Selenium::WebDriver::Point.new x, y
```
How do I move Ferrum's Chrome window? Or maybe pass coordinates with `Browser.new`?

**Comment by Mifrill** [comment]
See the example to set the position for the browser window bounds:
https://github.com/rubycdp/ferrum#position
