### ISSUE TITLE
wait_for_idle stop working in each block

### ISSUE THREAD

**Issue by balt5r** [rubycdp/ferrum#124]
Hi guys! Just started to use the framework and I like it so far. 
Happy to start collaborating from now on.

I identified a bug, take a array of URL 

```
[url_1, url_2, ...].each do |url|
  browser.network.wait_for_idle
  browser.goto(url)
end
```

`wait_for_idle` will work well for the first url, but will timeout and throw error for all the other ones. 

For now, I tweaked the code of the gem to break the timeout, but it would be useful to be able to use `wait_for_idle` in such case.

**Comment by Nakilon** [comment]
> `wait_for_idle` will work well for the first url, but will timeout and throw error for all the other ones

In my case it hangs on the first time: https://github.com/rubycdp/ferrum/issues/114#issue-695303688

**Comment by gmisura** [comment]
https://github.com/rubycdp/ferrum#wait_for_idleoptions

Seems you have your order mixed up:
go_to, then wait_for_idle

**Comment by route** [comment]
@balt5r `wait_for_idle` should only be used in cases where you expect ajax requests to finish and you don't know when it's going to happen. If you need to visit a few different urls not related to each other sequentially I recommend creating new page for each one:

```ruby
[url_1, url_2, ...].each do |url|
  begin
    page = browser.create_page
    page.goto("/ferrum/headers")
    do_some_stuff
  rescue => e
    # handle
  ensure
    page&.close
  end
end
```
