### ISSUE TITLE
How to focus on a new tab

### ISSUE THREAD

**Issue by balt5r** [rubycdp/ferrum#127]
Creating a new tab like that:

```
browser.create_page
```

however, `browser.page` still point to the previous tab. How to focus on the new tab?

**Comment by route** [comment]
`browser.page` is a default page.
```
page = browser.create_page
page.bla
```

**Comment by balt5r** [comment]
@route is there a way to change the browser default page dynamically?

**Comment by route** [comment]
I don't think it's necessary. All the methods that are available on `browser` are delegated to default page, then why not just start using page instead of the whole browser.
