### ISSUE TITLE
save cookies and retrieve them

### ISSUE THREAD

**Issue by balt5r** [rubycdp/ferrum#128]
it would be a nice addition. 

see [capybara session-keeper](https://github.com/kyamaguchi/capybara-sessionkeeper)

**Comment by route** [comment]
I think like with capybara session keeper it deserves a fate of a dedicated gem. I'll put it to rubycdp namespace If you implement it, but I myself not going to work on it at least in near foreseeable future, because I have a lot to work on in Ferrum.
