### ISSUE TITLE
Browser is dead or given window is closed

### ISSUE THREAD

**Issue by balt5r** [rubycdp/ferrum#129]
I have several intances of Ferrum running in production and I'm getting this error a lot:

```
Browser is dead or given window is closed
```

Any clue where the problem comes from?

**Comment by balt5r** [comment]
Just to give you an idea, the error is happening a lot. ~200 times per hour 

<img width="291" alt="image" src="https://user-images.githubusercontent.com/74566490/100153056-47df4800-2eac-11eb-824c-012aa1319706.png">

**Comment by route** [comment]
I think you have not enough memory, but anyways there's too little information for me to even suggest.

**Comment by balt5r** [comment]
@route I'm running Ferrum instances on 1GB memory droplets, the smallest size possible. Do you think there is a way to optimize this without resizing? Getting more and more of errors

<img width="309" alt="image" src="https://user-images.githubusercontent.com/74566490/100488815-14edbc00-3119-11eb-8889-df2877f5d0cf.png">

**Comment by balt5r** [comment]
I've done some research, it comes from the CPU. I'm running tests right now

**Comment by balt5r** [comment]
CPU isn't the problem. I upgraded the droplet and i still get the error.

I'm going to try some different version of chrome. Right now I'm on `87.0.4280.66`

**Comment by balt5r** [comment]
@route I've moved to 2VCPU and 2gb memory but I still get the same error. I don't think it comes from that.

**Comment by nurettin** [comment]
Can you monitor available RAM? Are you running any javascript on the browser like `fetch` that might be leaking memory?

**Comment by route** [comment]
@nurettin We have settled this down in PM, that was another issue. All good ;)

**Comment by popcorn** [comment]
@route - what was the issue? I'm seeing the same problem

**Comment by route** [comment]
@popcorn RAM and something really related to the crawler itself
