### ISSUE TITLE
local SSL Certificate Error

### ISSUE THREAD

**Issue by Daniel-ltw** [rubycdp/ferrum#131]
https://chromedevtools.github.io/devtools-protocol/tot/Security/#method-setIgnoreCertificateErrors

Is there a way to deal with this? 
I have a caddy server and it could provide internal ssl certs for localhost/docker host/containers. 
Is there a way around this ssl cert error problem? 

I tried a few chrome commandline arguments around certs and they do not seem to do a thing.

**Comment by Mifrill** [comment]
@Daniel-ltw try `--ignore-certificate-errors` option for chrome by `browser_options`

https://peter.sh/experiments/chromium-command-line-switches/#ignore-certificate-errors-spki-list

https://github.com/rubycdp/ferrum#customization

>   * `:browser_options` (Hash) - Additional command line options,
      [see them all](https://peter.sh/experiments/chromium-command-line-switches/)
      e.g. `{ "ignore-certificate-errors" => nil }`

**Comment by Daniel-ltw** [comment]
I think I did try that and it did not work for me.

**Comment by Mifrill** [comment]
@Daniel-ltw thanks for the response.
Please check this code one more time and provide more details:
```
        browser = Browser.new(browser_options: { "ignore-certificate-errors" => nil })
        
        expect(browser.command("Browser.getBrowserCommandLine")["arguments"]).
          to include("--ignore-certificate-errors")
```
What the gem version?
Share the log with errors, please

**Comment by Mifrill** [comment]
I think it can be closed now. Would reopen if the issue gets confirmed.
@Daniel-ltw feel free to raise reopen by providing more details.
