### ISSUE TITLE
Equivalent of Puppeteer's `evaluateOnNewDocument`

### ISSUE THREAD

**Issue by alexanderadam** [rubycdp/ferrum#132]
See the [`evaluateOnNewDocument`](https://github.com/puppeteer/puppeteer/blob/b57f3fcd5393c68f51d82e670b004f5b116dcbc3/docs/api.md#pageevaluateonnewdocumentpagefunction-args) documentation for details.

Interesting bit for me is, that

> [T]he function is invoked after the document was created but before any of its scripts were run.

This makes it pretty mighty and it seems that [other Ruby libraries aren't supporting this at the moment yet](https://stackoverflow.com/questions/57487802/watir-equivalent-to-evaluateonnewdocument).

**Comment by route** [comment]
This is what `extensions` are for https://github.com/rubycdp/ferrum#customization

**Comment by alexanderadam** [comment]
Any particular reason what would speak against a native integrated `evalulate_on_new_document` or similar?

**Comment by route** [comment]
None, I started Cuprite project first and tried to make it compatible with Poltergeist, thus :extensions appeared. This project was extracted from Cuprite, I don't mind having dedicated method, if you open a PR gladly merge it.

**Comment by alexanderadam** [comment]
Okay, good. Would you consider reopen this issue then please? :wink:

**Comment by skyeagle** [comment]
just in a case, someone is looking for an example of doing it with [cuprite](github.com/rubycdp/cuprite) and extensions:

```ruby
Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(
    app,
    window_size: [1200, 800],
    extensions: [
      { source: "console.log('Page.addScriptToEvaluateOnNewDocument triggered')" },
    ],
  )
end
```
