### ISSUE TITLE
Handling of canceled requests

### ISSUE THREAD

**Issue by julioolvr** [rubycdp/ferrum#135]
I'm still not 100% sure about this, but I've been trying to ensure all requests where handled before wrapping up each test case with `page.driver.wait_for_network_idle` in an `after` hook. Even though using Chrome in non-headless mode I was able to see al requests being completed, according to Ferrum the network still wasn't idle.

I grabbed the pending requests with `page.driver.network_traffic.select(&:pending?)` and started comparing and noticed that the supposedly pending requests where the ones cancelled by the browser (for instance, by using `AbortController` to cancel a request done with `fetch`).

I found the [`loadingFailed`](https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-loadingFailed) event in the devtools protocol so I tried something like this as a quick test:

```ruby
@page.on("Network.loadingFailed") do |params|
  exchange = select(params["requestId"]).last

  if exchange && params['canceled']
    puts 'Found exchange, setting arbitrary error'
    exchange.error = :canceled
  end
end
```

And that seems to properly consider canceled requests as "finished". There might be _a lot_ I'm overlooking since this is in the context of a big app with plenty of moving pieces but since I saw a clear improvement I figured I'd brought it up.

**Comment by route** [comment]
That sounds right. I think I had a fight with requests before, if you could come up with a quick tests to run and see the issue or PR I'd gladly merge it, thanks for this investigation!

**Comment by julioolvr** [comment]
Awesome, I'll give it a shot over the weekend 👍

**Comment by route** [comment]
Closing this then!
