### ISSUE TITLE
Save as MHTML?

### ISSUE THREAD

**Issue by npearson72** [rubycdp/ferrum#137]
I noticed that ferrum accepts `browser_options` and that chromium can take `--save-page-as-mhtml`:

https://peter.sh/experiments/chromium-command-line-switches/#save-page-as-mhtml

Is it possible for ferrum to save the mhtml file to the file system much like it does with screenshots?

**Comment by route** [comment]
No this won't work, I added `mhtml` https://github.com/rubycdp/ferrum#mhtmloptions--string--integer use master
