### ISSUE TITLE
Very verbose @xvfb initialization warnings on 2.7.2

### ISSUE THREAD

**Issue by wflanagan** [rubycdp/ferrum#146]
/Users/wflanagan/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/ferrum-0.9/lib/ferrum/browser/process.rb:90: warning: instance variable @xvfb not initialized

I'm working on implementing something using Ferrum. In my 150 or so tests, I see this warning about 300 times. 

I have set :xvfb => false in the initialization.  

Is there something else to do to get this noise to go away? 😄

**Comment by route** [comment]
Thanks, fixed in master!
