### ISSUE TITLE
Default time out

### ISSUE THREAD

**Issue by rubyFeedback** [rubycdp/ferrum#163]
Hey there,

New user of ferrum.

I am working through the examples.

But when doing this:

    browser = Ferrum::Browser.new

I get:

Ferrum::ProcessTimeoutError (Browser did not produce websocket url within 2 seconds)

I am starting chrome as superuser via:

    chrome --no-sandbox

Not sure if that matters.

The thing is the timeout message confuses me. As a new user I ask myself what
to do next? Could the message be more useful, or alternatively, could it just
work? :D (I really have no idea why the message appears right now; I am more
focused on trying to get the first example to work but it does not. I think it should
ideally work, and if not, the user should get information how to fix the issue IMO.)

Thanks.

**Comment by route** [comment]
I increased default timeouts in master. But if you haven’t figured it out yet just increase process_timeout. I’ll try to make error human readable.
