### ISSUE TITLE
Instance host entry / custon DNS entries in Ferrum Browser

### ISSUE THREAD

**Issue by alexanderadam** [rubycdp/ferrum#164]
There's probably a proper name for it, but is there a possibility to have something like custom host entries for the browser instance without having to setup a separate DNS server or to modify the local `hosts` file?

So a solution for pointing a hostname (i.e. `example.org`) to another ip (i.e. `192.168.123.123`) for the browser session.

Is there a solution with an extension for that or maybe even something integrated?

**Comment by route** [comment]
Do you use Docker? Otherwise loopback should suffice

**Comment by alexanderadam** [comment]
No and it should also be something that's independent from the base system (so no hostfile, firewall, etc.)

Well, then I will close this if you don't know any integrated possibility with Chrome/CDP/Ferrum.

**Comment by route** [comment]
No sorry, don’t know any
