### ISSUE TITLE
Document how to download files

### ISSUE THREAD

**Issue by alexanderadam** [rubycdp/ferrum#169]
I probably just missed this but I cannot find the download documentation.

It's probably related to [the `:save_path` option](https://github.com/rubycdp/ferrum/blob/f0cec32c489d204ebf562fd29781f09b337e7450/lib/ferrum/page.rb#L230) but I cannot find any information about that either.

Do you have any advice?

I'm not sure whether this is relevant but there are at least two relevant cases:

1. Explicit downloads that are triggered within ferrum (i.e. "click on a link and save there result" or "download this (background) image")
2. Implicit downloads that are triggered by the server (i.e. with HTTP header `Content-Disposition: attachment` or HTML links like `<a href="foo" download>…`)

**Comment by route** [comment]
I'll try to add test for that but I think it should just store file in the given folder, basically that's it

**Comment by alexanderadam** [comment]
A test would be great! 👍 I guess I missed something somehow.
Now I'm using an ugly workaround (but at least it's working 😉).

Thank you for looking into this.

**Comment by marcoschicote** [comment]
Hi! 
I'm in need of this too. I need to save an image that is part of a web page. Is it possible to download only that image?

Thanks!

PS: @alexanderadam if you can share the ugly workaround I would appreciate it!

**Comment by alexanderadam** [comment]
> @alexanderadam if you can share the ugly workaround I would appreciate it!

hola Marcos, I'm sure afterwards you'd wish that I didn't tell you :laughing: 

:warning: **Disclaimer: this only works for documents that can be viewed within the browser!** :warning:

But at least it is working in my case. I'm sure that there's a native version in ferrum but I wasn't able to find out how (therefore I created this ticket).

```ruby
require 'mhtml' # for parsing mhtml - https://github.com/benjineering/mhtml_rb

download_directory = 'your/download_directory/'
browser.go_to download_url

# we are storing the current page with all assets within a temporary directory
Dir.mktmpdir do |dir|
  path = "#{dir}/tmp.mhtml"
  browser.mhtml(path: path)
  mhtml = Mhtml::RootDocument.new(File.read(path))

  # extracting all assets from mhtml
  mhtml.sub_docs.each do |file|
    file_name = File.join(download_directory, File.basename(mhtml.sub_docs.first.file_path))
    File.write(file_name, file.body)
  end

browser.back # going back since we don't want to pollute the running session
```

**Comment by marcoschicote** [comment]
Thanks @alexanderadam!
As I only needed to capturen an image I ended up doing this:
```ruby
      browser.screenshot(
        path: 'file.jpg',
        selector: 'img[id$=capimg]'
      )
```

**Comment by alexanderadam** [comment]
Also a nice workaround. :+1:

**Comment by nickhammond** [comment]
Ferrum will save any file that would normally prompt you to save the file when using Chrome. I'd recommend setting the `save_path` since you probably don't want the file to be saved in one of your application folders and in persistent/mounted storage somewhere.

```
browser = Ferrum::Browser.new(save_path: "#{Rails.root}/documents")
browser.at_css(".download").click
```

If a download takes some time there's a [wait setting](https://github.com/rubycdp/ferrum/issues/179) you can set or you can wait for the download to complete by checking the presence of the file on disk if it's deterministic.

**Comment by alexanderadam** [comment]
> Ferrum will save any file that would normally prompt you to save the file when using Chrome. I'd recommend setting the `save_path` since you probably don't want the file to be saved in one of your application folders and in persistent/mounted storage somewhere.
> 
> ```
> browser = Ferrum::Browser.new(save_path: "#{Rails.root}/documents")
> browser.at_css(".download").click
> ```
> 
> If a download takes some time there's a [wait setting](https://github.com/rubycdp/ferrum/issues/179) you can set or you can wait for the download to complete by checking the presence of the file on disk if it's deterministic.

And how to use the browser functionality `save as`?
i.e. downloading an image where the server headers won't send `Content-Disposition: attachment` or something like that?

**Comment by nickhammond** [comment]
@alexanderadam I haven't had a use for that but I suppose you could grab the browser's current URL and just use open-uri to download the image. I'd also be curious what `body` returns from the browser for an image like that, wonder if you could just write the image by fetching the current body, haven't tried that though.

**Comment by alexanderadam** [comment]
> @alexanderadam I haven't had a use for that but I suppose you could grab the browser's current URL and just use open-uri to download the image.

This would only possible for resources that are public. If you need a session to access them, you would also need to exchange cookies. And if things like websockets are involved it might even become more messy. :wink:

**Comment by esergion** [comment]
This approach always works for me, just a simple url fetching using HTTP module:
https://gist.github.com/esergion/a3a91746cf2779dce8f013bf22dd7da9

You always can get cookies after authorization:
```
browser.go_to("example.url")
# Authorize
cookies = browser.cookies.all.values.map do |c|
  {
    name: c.name,
    value: c.value,
  }
end

content = Downloader.fetch(URL, cookies).body
```

**Comment by hkmaly** [comment]
@alexanderadam I'm not entirely sure as I didn't tested it yet, but wouldn't the method mentioned in #181 be usable for saving any files, not just XHR responses? So, to save file named `privateUndownloadableImage.png` from page `coolimages.com` you could try
```
require 'ferrum'

browser = Ferrum::Browser.new
browser.go_to("https://coolimages.com/")
response = browser.network.traffic.find { |exchange|
  exchange.request.url.match?(/privateUndownloadableImage.png/)
}.response
response.body
```

**Comment by mtomov** [comment]
Hi guys, 

managed to get it to work with this:

```ruby
module System
  module DownloadHelpers
    TIMEOUT = 10
    PATH = Rails.root.join("tmp/capybara")

    def downloads
      Dir[PATH.join("*")].reject { |f| File.directory?(f) }
    end

    def download
      downloads.first
    end

    def download_content
      wait_for_download
      File.read(download)
    end

    def wait_for_download
      Timeout.timeout(TIMEOUT, Timeout::Error) do
        sleep 0.1 until downloaded?
      end
    end

    def downloaded?
      !downloading? && downloads.any?
    end

    def downloading?
      downloads.grep(/\.crdownload$/).any?
    end

    def clear_downloads
      FileUtils.rm_f(downloads)
    end
  end
end

RSpec.configure do |config|
  config.include System::DownloadHelpers, type: :system

  config.around(:each, type: :system) do |example|
    clear_downloads
    example.run
    clear_downloads
  end
end
```

using this guide https://evilmartians.com/chronicles/system-of-a-test-setting-up-end-to-end-rails-testing


so having this in:

```ruby
Capybara.save_path = ENV.fetch("CAPYBARA_ARTIFACTS", "./tmp/capybara")
```

The way it works is to look for files in this `save_path` directory, and clear them up between runs. There might be a better way, but this does work. Let me know if you have improvement suggestions!

**Comment by nickhammond** [comment]
I tried to put this in a fork for a PR but it looks like forking is locked, here's a simple download example:

spec/download_spec.rb
``` ruby
module Ferrum
  describe Browser do
    context "download support" do
      let(:browser) do
        Ferrum::Browser.new(
          base_url: Ferrum::Server.server.base_url,
          save_path: '/tmp/ferrum'
        )
      end

      it 'saves an attachment' do
        browser.go_to('/attachment.pdf')

        expect(File.exists?('/tmp/ferrum/attachment.pdf')).to be true
      end
    end
  end
end
```

spec/support/application.rb - Add a request endpoint
``` ruby
get "/attachment.pdf" do
  path = "/tmp/ferrum/attachment.pdf"
  FileUtils.touch(path)

  attachment(path, :attachment)
end
```

Add a note to the readme within the `browser_options` section:
```
:save_path` (String) - Path to save screenshots, PDF, mhtml, and attachment requests
```

**Comment by nickhammond** [comment]
@route normally it should but it looks like forking has been disabled either at the org or repo level.

This is what I see when I go to fork the repository:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/17698/163416263-7b282e63-72a0-4ddc-984f-485fddef5083.png">

**Comment by route** [comment]
@nickhammond maybe it's a glitch, try using another browser or sign-in again. Dunno I just checked from my account and my wife's account and it worked... I'll ask a couple of more friends, but it should be impossible for open source repos in general.

**Comment by nickhammond** [comment]
@route Ha, I already had a fork. Should have checked, usually it just takes you to your fork.

**Comment by route** [comment]
Ok since PR regarding `save_path` is merged I'm closing it. That's the only feature to download files in the background, all the rest methods have explicit path argument.

**Comment by Nakilon** [comment]
Since the filename can be unknown in advance I'm about to prefer @hkmaly's approach.
I just wonder if there are any methods to keep track on the current "position" in the `network` requests thing. Like...
```ruby
finished_or_started_requests = track do
  # and here I click stuff to make the file download
end
```
