### ISSUE TITLE
Implement Tracing

### ISSUE THREAD

**Issue by route** [rubycdp/ferrum#171]
https://github.com/puppeteer/puppeteer/blob/v8.0.0/docs/api.md#class-tracing

**Comment by Mifrill** [comment]
:notebook:
- https://chromedevtools.github.io/devtools-protocol/tot/Tracing/
- https://github.com/ChromeDevTools/devtools-frontend/blob/322507ed6425d6ac450a17cfb8de8a81136cca4c/front_end/generated/InspectorBackendCommands.js#L2728-L2771
- https://github.com/microsoft/playwright/blob/c373986ca0b91b76d4910ce0617b55e50934114c/packages/playwright-core/src/server/chromium/crBrowser.ts#L238-L274
- https://github.com/puppeteer/puppeteer/pull/7413
- https://github.com/YusukeIwaki/puppeteer-ruby/blob/a9018bd39c0f6dcb7988e5ab53762aa1922ad8ce/lib/puppeteer/tracing.rb#L1-L72
