### ISSUE TITLE
Blank screenshot

### ISSUE THREAD

**Issue by glaucocustodio** [rubycdp/ferrum#172]
hi guys, I am playing with vessel, trying to take a screenshot using ferrum's api (`page.browser.screenshot(path: "tmp/foo.png"`) but I just get a blank image no matter the options I pass.

I suspect it might be an issue with the command `Page.captureScreenshot`.

ps: I've also added a `sleep 5` before printing to make sure the page is fully loaded.

Any tips?

**Comment by route** [comment]
Why would you call `page.browser` it's `page.screenshot(path: "tmp/foo.png")`.

**Comment by glaucocustodio** [comment]
Oops, sorry, `page.screenshot` works!

I found out `page.browser` by inspecting the elements with `ls`. I will open a PR on vessel documenting how to take screenshots. 

Thank you.
