### ISSUE TITLE
One extra base chrome window is spawned

### ISSUE THREAD

**Issue by rrnair-98** [rubycdp/ferrum#174]
To reproduce this instantiate the browser instance first
`
def setup_browser
      Ferrum::Browser.new(:browser_path => chrome_path, :headless => @headless, :slow_mo => 5, :timeout => 20,
                          :browser_options => browser_switches_to_hash)
end
`
At this point one window of chrome exists
![Screenshot from 2021-03-11 13-24-33](https://user-images.githubusercontent.com/30407158/110754331-b71b5500-826d-11eb-99a2-cec7ef1d308b.png)

In some other class that has this browsers reference

`
browser.goto("some.url")
`
Another window of chrome is spawned.
![Screenshot from 2021-03-11 13-28-08](https://user-images.githubusercontent.com/30407158/110754364-c0a4bd00-826d-11eb-99ab-5ca688b1ba43.png)
The question is how can we have this working on the first page itself.
I tried getting the reference to the page from the contexts, but it ended up creating another page.

**Comment by route** [comment]
It should have been fixed in the latest release, what version you are on?

**Comment by rrnair-98** [comment]
Right now Im running version 0.9, the problem with 0.10.2 was that xpath() always lead to a JavascriptException, stating '=>' is an illegal token

**Comment by route** [comment]
Sorry I forgot I didn't release it yet. Can you try using master branch? `gem 'ferrum', github: 'rubycdp/ferrum'` and check if it creates two windows? Then I can take a look at the other issue if you attach logs here or to my email.

**Comment by route** [comment]
Looking at the info you sent I didn't find issues with Ferrum all are site specific stuff
