### ISSUE TITLE
DeadBrowserError and browser restart

### ISSUE THREAD

**Issue by vakuum** [rubycdp/ferrum#177]
I use Cuprite as a JavaScript driver for Capybara and sometimes the Chrome process crashes and Ferrum raises a DeadBrowserError at https://github.com/rubycdp/ferrum/blob/v0.11/lib/ferrum/browser/client.rb#L45.

After that, all following tests turn red because Ferrum doesn't restart the browser.

If I change https://github.com/rubycdp/ferrum/blob/v0.11/lib/ferrum/browser/client.rb#L45 as follows, then only the first test after the crash turns red:

```
-        raise DeadBrowserError if data.nil? && @ws.messages.closed?
+        if data.nil? && @ws.messages.closed?
+          @browser.restart
+          raise DeadBrowserError
+        end
```

An automatic browser restart does also happen at https://github.com/rubycdp/ferrum/blob/v0.11/lib/ferrum/browser.rb#L91.

**Comment by route** [comment]
The idea was to bubble up it to outer classes because it out of scope of client class. So maybe we miss it in Page class?

**Comment by route** [comment]
Ferrum won't restart automatically, it makes usage as straightforward as possible.
It should be Cuprite responsibility. Please open an issue in https://github.com/rubycdp/cuprite if it's still the case.
