### ISSUE TITLE
Blank screenshot only with headless browser

### ISSUE THREAD

**Issue by marcoschicote** [rubycdp/ferrum#180]
Hi
I'm getting a blank screenshot with the following code:

```ruby
def initialize_browser
        browser = Ferrum::Browser.new(headless: true)
        # browser.network.clear(:traffic)
        browser.go_to('https://www.afip.gob.ar/aportesenlinea/')
        browser.at_xpath("//a[@title='Consultá sin Clave Fiscal']").click
        # browser.network.wait_for_idle
        # browser.at_xpath('//body').wait_for_stop_moving
        # sleep(10)
        browser.screenshot(path: 'showme.png')
        browser
end
```

I'm leaving the commented code as this I've tried and have no impact. If I change the `headless` property on browser creation I get the right screenshot. Can anyone help me?

Thanks!

------
UPDATE: Seams to be a problem related to my computer, working fine on server.

**Comment by route** [comment]
@marcoschicote can you try changing Chrome version? What OS do you use? People had issues with linux and snap when working with Chrome because snap has some kind of wrapper

**Comment by marcoschicote** [comment]
Chrome: `Version 90.0.4430.93 (Official Build) (x86_64)` 
OS: macOS Big Sur 11.3

**Comment by route** [comment]
If I were you I'd try different Chrome versions, it looks like it's Chrome's issue not Ferrum's

**Comment by alexanderadam** [comment]
I would also try to play around with GPU related things (i.e. disabling/enabling webgl, gpu-compositing or hardware acceleration).

**Comment by route** [comment]
Closing for now, needs some answers
