### ISSUE TITLE
Outdated CHANGELOG.md

### ISSUE THREAD

**Issue by Mifrill** [rubycdp/ferrum#192]
https://github.com/rubycdp/ferrum/blob/master/CHANGELOG.md

Last described version in CHANGELOG: [0.6.2](https://github.com/rubycdp/ferrum/blob/v0.11/CHANGELOG.md#062---oct-30-2019)

Current version: [0.11](https://github.com/rubycdp/ferrum/compare/v0.10.2...v0.11)

https://github.com/rubycdp/ferrum/commit/006c5fc385596c218402de8b0d24dbe6739f1c72#commitcomment-48149824
https://github.com/rubycdp/ferrum/commit/1658e0005dd8eae7618f6316b60f055d50f9adb7#commitcomment-38352770

References:
- [ ] 0.11
- [ ] 0.10.2
- [ ] 0.10.1
- [ ] 0.10
- [ ] 0.9
- [ ] 0.8
- [ ] 0.7
- [x] 0.6.2 [[0.6.0]/[0.6.1]/[0.6.2]](https://github.com/rubycdp/ferrum/pull/63)
- [x] 0.6.1 [[0.6.0]/[0.6.1]/[0.6.2]](https://github.com/rubycdp/ferrum/pull/63)
- [x] 0.6 [[0.6.0]/[0.6.1]/[0.6.2]](https://github.com/rubycdp/ferrum/pull/63)
- [x] 0.5 [[0.5.0]](https://github.com/rubycdp/ferrum/pull/69)
- [x] 0.4 [[0.4.0]](https://github.com/rubycdp/ferrum/pull/76)
- [x] 0.3 [[0.3.0]](https://github.com/rubycdp/ferrum/pull/98)
- [x] 0.2.1 [[0.1.0.alpha] - ... - [0.2.1]](https://github.com/rubycdp/ferrum/pull/123)
- [x] 0.2 [[0.1.0.alpha] - ... - [0.2.1]](https://github.com/rubycdp/ferrum/pull/123)
- [x] 0.1.2 [[0.1.0.alpha] - ... - [0.2.1]](https://github.com/rubycdp/ferrum/pull/123)
- [x] 0.1.1 [[0.1.0.alpha] - ... - [0.2.1]](https://github.com/rubycdp/ferrum/pull/123)
- [x] 0.1.0 [[0.1.0.alpha] - ... - [0.2.1]](https://github.com/rubycdp/ferrum/pull/123)
- [x] 0.1.0.alpha [[0.1.0.alpha] - ... - [0.2.1]](https://github.com/rubycdp/ferrum/pull/123)

**Comment by route** [comment]
We are close :)

**Comment by route** [comment]
I think I finished it.
