### ISSUE TITLE
Customize chrome startup flags

### ISSUE THREAD

**Issue by borlafdev** [rubycdp/ferrum#193]
Hi,

I was having problems connecting with a third party API in some websites (The website loads, but the third party returns a 403 error when requesting access token)

I've made many tests, from different IPs, incognito / non incognito mode, tested puppeteer & it works. After that compared the startup flags chrome vs puppeteer  and located the one that was causing the error ```--disable-web-security```

I've disabled if vía monkey-patching (overriding constant in an initializer), but i would like to create a flag like ```:ignore_startup_flags``` and call Options#except also with the passed flags (Like https://github.com/rubycdp/ferrum/blob/master/lib/ferrum/browser/options/chrome.rb#L69)

I can make a PR & write some tests

**Comment by route** [comment]
That's already handled by https://github.com/rubycdp/ferrum/issues/67

**Comment by borlafdev** [comment]
Thanks & sorry, didn't see it on master... Will look better next time.

**Comment by route** [comment]
No problem at all. I think it's our fault with poor documentation
