### ISSUE TITLE
Hangs with debugger

### ISSUE THREAD

**Issue by molfar** [rubycdp/ferrum#195]
I tried to use debug gem, but when I execute binding.break in my code, Ferrum stops respond to any further commands with Ferrum::TimeoutError

**Comment by route** [comment]
Yes it's a known issue, I assume it's because debugger stops all the threads and the one responsible for passing commands to Chrome is also paused. I'm looking forward to https://github.com/ruby/debug because they say 'Support threads (almost done) and ractors (TODO).'

**Comment by molfar** [comment]
I also opened an issue with Debug gem  https://github.com/ruby/debug/issues/295

**Comment by route** [comment]
It looks like it's not Ferrum issue anyways. Closing
