### ISSUE TITLE
Add README for how to get a frame by a finder.

### ISSUE THREAD

**Issue by zw963** [rubycdp/ferrum#198]
Following is a example:

```rb
browser = Ferrum::Browser.new(headless: true, browser_options: { 'no-sandbox': nil })
browser.goto 'http://ip111.cn'
browser.network.wait_for_idle(timeout: 10)

p = browser.css('div.card-body p')[2]

body = p.at_css('iframe').frame.body  # <= this `at_css('iframe').frame` usage was not menthioned on README`

```

And, is there a easy to to parse the above body directly to extract the text content? (without need Nokogiri)

e.g.  following is iframe `body` return string, how to extract `152.32.111.111 香港`.

"<html><head><meta charset=\"utf-8\"><meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\"><meta http-equiv=\"Pragma\" content=\"no-cache\"><meta http-equiv=\"Expires\" content=\"0\"></head><body style=\"text-align: center; font-family: Helvetica,Arial,sans-serif; font-size: 14px; \" marginwidth=\"0\" marginheight=\"0\">152.32.111.111 香港 \n\n</body></html>"

Thank you.

**Comment by zw963** [comment]
> p.at_css('iframe').frame.at_xpath("//body").text

Thank you for help. 

> I think you are looking for `frames`:

Yes, i know this, i find `frames` is mention on README, but never mention the useful `frame` method, for my case, i need findout
 `the iframe within current p element`, so, use frame is better, but, i have to test it many times to find out this useful method.

so , i propose add this into readme.

**Comment by Mifrill** [comment]
@zw963 yeah, thank you for point out it, our documentation needs to be improved for sure. PR is always welcome.
[This part](https://github.com/rubycdp/ferrum#frame-1) should be extended with your example

**Comment by zw963** [comment]
> @zw963 yeah, thank you for point out it, our documentation needs to be improved for sure. PR is always welcome. [This part](https://github.com/rubycdp/ferrum#frame-1) should be extended with your example

i thought `frame` should add to `frames` sections, my english is bad, maybe i can try add it anyway.

**Comment by Mifrill** [comment]
@zw963 I think, it's nice to have it in both:
1. https://github.com/rubycdp/ferrum#frame-1
Because `at_css('iframe').frame` it is exactly `Node#frame` section:
https://github.com/rubycdp/ferrum/blob/006c5fc385596c218402de8b0d24dbe6739f1c72/lib/ferrum/node.rb#L25-L27
```ruby
p.at_css('iframe').is_a?(Ferrum::Node)
=> true
```
2. and in https://github.com/rubycdp/ferrum#frames, probably as a reference to https://github.com/rubycdp/ferrum#frame-1 with the use-case

**Comment by zw963** [comment]
>  Because `at_css('iframe').frame` it is exactly `Node#frame` section:

Yes, it usage not same as watir,  this may confusing some newbie like me.

```
# watir usage
element.p.iframe.body.wait_until(&:present?).text
```

**Comment by zw963** [comment]
create a PR for this, #199, please check.
