### ISSUE TITLE
"_cuprite is undefined" error, `execution_id` of `main_frame` can be overwritten. 

### ISSUE THREAD

**Issue by leschenko** [rubycdp/ferrum#25]
`execution_id` of `main_frame` can be overwritten during `Runtime.executionContextCreated` event for chrome-extension for example.
I temporary fixed this with 
`frame.execution_id = context_id unless frame.instance_variable_get(:@execution_id)`
I faced this issue in Opera browser which creates execution context for`Video handler` extension for every frame.

**Comment by route** [comment]
Do you experience such issue with chrome or it's opera only?

**Comment by leschenko** [comment]
I think this is not Opera issue. There was "assign once" behavior in the previous realization of cuprite. It seems that it was right flow.
https://github.com/machinio/cuprite/blob/a11a6cc8537b3cd23bb7564f1a9fc3083747e7f4/lib/capybara/cuprite/browser/frame.rb#L89

**Comment by route** [comment]
@leschenko could you please show debug log where the execution context is being set a few times? I cannot reproduce this issue because I don't have such plugins in the browser and don't understand why it should be triggered for the same frame a few times...

**Comment by route** [comment]
@leschenko nm I think I got it
