### ISSUE TITLE
Navigate through an incognito session

### ISSUE THREAD

**Issue by rudasa** [rubycdp/ferrum#251]
Hi folks, I've tried by adding `'incognito' => nil` option to `browser_options` without any luck, Ferrum is still navigating with the regular profile and not incognito (the one that uses the gray color). I need to use the incognito profile because even when the `user data dir` is[ different between each `Ferrum` instance](https://github.com/rubycdp/ferrum/blob/9f243692a1f9b6e238b2b7219c0303527572860c/lib/ferrum/browser/process.rb#L78), for some reason the target site is detecting my recurrent visits and disabling some features but it works fine when I use an incognito session.

Any clue to work around it will be very appreciated, thanks!

**Comment by route** [comment]
Every session of Ferrum is an incognito mode. There are many techniques of detecting your browser.
You might need something like https://github.com/rubycdp/ferrum/issues/142
