### ISSUE TITLE
Improve the flow of retrieving and setting Cookies

### ISSUE THREAD

**Issue by gbaptista** [rubycdp/ferrum#253]
Today, I have to set cookies through:

```ruby
browser.cookies.set(name: "stealth", value: "omg", domain: "google.com")
```

This is great, but if I want, for example, to use a retrieved cookie:

```ruby
some_cookie = browser.cookies.all.values.first
# #<Ferrum::Cookies::Cookie:0x00007f96b038e6b0
#  @attributes=
#   {"name"=>"stealth",
#    "value"=>"omg",
#    "domain"=>"google.com"}>

browser.cookies.set(some_cookie)
# => ArgumentError: wrong number of arguments (given 1, expected 0)
```

To make the cookie object comply with the expected API, I need to workaround:

```ruby
adapted_cookie = {}

some_cookie.instance_variable_get('@attributes').each do |key, value|
  cookie[key.to_sym] = value
end

browser.cookies.set(**adapted_cookie)
```

Why would that be important? For my use case, I store cookies and then retrieve them at another moment in the future:

```ruby
# Save:
File.write('cookies.bin', Marshal.dump(browser.cookies.all))

# Load:
Marshal.load(File.read('cookies.bin')).values.each do |raw_cookie|
  adapted_cookie = {}
  raw_cookie.instance_variable_get('@attributes').each do |key, value|
    adapted_cookie[key.to_sym] = value
  end
  browser.cookies.set(**adapted_cookie)
end
```

Some ideas to improve this flow:

- Expose the `@attributes`, so I don't need to `instance_variable_get`;
- Create a `to_h` method to have access to a hash accepted in `cookies.set`;
- Just allow `cookies.set` to accept instances of `Ferrum::Cookies::Cookie`.

**Comment by route** [comment]
Totally agree it's definitely not thoroughly thought now and needs improvement.

**Comment by gbaptista** [comment]
Closed by:
- #256
