### ISSUE TITLE
Upload/Attach File on button Click

### ISSUE THREAD

**Issue by wonderer007** [rubycdp/ferrum#284]
Can we upload/attach file on a button click ?

I think https://github.com/rubycdp/ferrum#select_file might be what I am looking for but its missing documentation. 

I am trying this but

```
button = browser.at_xpath("//button[text() = 'Select File']")
button.select_file(Rails.root.join("file.png"))
```

It return error 

> Ferrum::BrowserError: Node is not a file input element

**Thank you so much for this beautiful library**

**Comment by ttilberg** [comment]
You are calling the method correctly, but the node you are calling it on should be an `<input>` element, not a button. Does the page you’re interacting with have a `<form>` element with a file `<input>` value?

**Comment by wonderer007** [comment]
Yes, page has `<form>` element and a file `<input type="text">` element inside it. This form is present inside a pop up. I am able to open the pop with the click though. But not able to attach file with it. Now tried this

```
browser.at_xpath("//input").select_file(Rails.root.join("file.png").to_s)
```
and it returns 

```
{}
```

But, nothing happens on the the pop up. 

Normal flow is, 

1. click on button (it opens a pop up)
2. click on upload (it opens file selector)
3. choose file and it shows preview

**Comment by wonderer007** [comment]
@ttilberg can we have drag/drop file ?

**Comment by wonderer007** [comment]
Actually calling click on file input element solved the issue @ttilberg thank you so much!
