### ISSUE TITLE
undefined method `url' for nil:NilClass

### ISSUE THREAD

**Issue by johncoates-st** [rubycdp/ferrum#297]
Getting this unhandled error sometimes on line 132:
https://github.com/rubycdp/ferrum/blob/425a747587fd4a76ed177ef8faf97672189fa232/lib/ferrum/page.rb#L130-L135

**Comment by route** [comment]
Fixed with https://github.com/rubycdp/ferrum/pull/298 but keep in mind that the request can be nil sometimes due to async nature of the browser.
