### ISSUE TITLE
Not actually loading pages, returns string instead

### ISSUE THREAD

**Issue by austinarchibald** [rubycdp/ferrum#305]
Several websites are returning a string that I cannot interact with. Here's one example. Any help?

```
browser = Ferrum::Browser.new.go_to "https://www.basketball-reference.com/leagues/NBA_2023.html"
=> "1A41C2B0782CD6E9E359634394008AAE"
page = Nokogiri::HTML(browser.body)
NoMethodError (undefined method `body' for "1A41C2B0782CD6E9E359634394008AAE":String)
browser.screenshot(path: "bref.png")
NoMethodError (undefined method `screenshot' for "1A41C2B0782CD6E9E359634394008AAE":String)
```

**Comment by route** [comment]
Please read the docs

**Comment by austinarchibald** [comment]
Can you point me in the right direction? I've been reading and researching for an hour or so and cannot find what I am doing wrong. Not having this issue with other web pages, just a couple of them.

**Comment by route** [comment]
browser = Ferrum::Browser.new

**Comment by austinarchibald** [comment]
That's exactly what I did. Still only returns a string that I cannot interact with. I'm not having an issue with most web pages. It doesn't work for this specific web page and a couple others, and I don't know why.

**Comment by route** [comment]
But that’s not what you exactly did assigning a string to browser variable

**Comment by austinarchibald** [comment]
I actually didn't condense it into one line or not use parentheses when I entered the commands, not sure why I did in the paste above, still get the same error. Following exactly as the docs show...
```
browser = Ferrum::Browser.new
browser = browser.go_to("https://www.basketball-reference.com/leagues/NBA_2023.html")
=> "F8FC3A61FD7D1996062798B08C6C3095"
page = Nokogiri::HTML(browser.body)
NoMethodError (undefined method `body' for "F8FC3A61FD7D1996062798B08C6C3095":String)
```

However, I think I may know what's going on. Earlier I tried this and got an image asking if I am a human. 
```
browser = Ferrum::Browser.new
browser = browser.go_to("https://www.basketball-reference.com")
browser.screenshot(path: "bref.png")
=> 60672
```
![bref](https://user-images.githubusercontent.com/12240843/199831135-17f6ba19-949d-4bd8-a897-89a650e02e64.png)

Weirdly, when I run those same commands again, I cannot repeat it, I get the NoMethodError for String again. But it worked once earlier. `NoMethodError (undefined method `screenshot' for "3D3A9AE96450886813B0648D7B04E45F":String)` 
I'm confused; it worked once, but not again (tried exiting rails console and entering back in). Could that javascript challenge be screwing things up.

**Comment by austinarchibald** [comment]
Ok, I needed remove `browser = ` before the go_to command. Thanks. 

The website yields a human verification challenge, which is another issue. Is there a way to successfully pass captcha each time?
![bref](https://user-images.githubusercontent.com/12240843/199836057-da148fcc-0dbd-4905-9481-5c2a580f6c31.png)
![bref2](https://user-images.githubusercontent.com/12240843/199836070-0826d83d-3127-4849-a056-d838715eb1f2.png)
