### ISSUE TITLE
Release 1.0

### ISSUE THREAD

**Issue by sandstrom** [rubycdp/ferrum#387]
Thanks for a great project! 🏅 

This project seems like a stable and mature one. Maybe it's time to release an 1.0 version.

Would help signal that it's ready for production use and in a stable place.

**Comment by route** [comment]
Before this there are still a couple of things I’d like to cover. First it’s new chrome mode aka headless=new and second all capybara tests for cuprite should be working, there are some skipped for now. After that we can bump to 1.0

**Comment by sandstrom** [comment]
@route Sounds great! 😄

**Comment by route** [comment]
So first part is done, second in progress. But I definitely keep releasing in my mind. No need for issue ;)
