### ISSUE TITLE
Exceptions within `.on()` blocks are mysteriously ignored

### ISSUE THREAD

**Issue by postmodern** [rubycdp/ferrum#396]
I noticed that exceptions raised within `.on()` blocks are mysterious ignored, and not even logged. This makes debugging errors within other code that's called within `.on()` blocks very difficult.

## Example Code

```ruby
require 'ferrum'

browser = Ferrum::Browser.new
browser.network.intercept
browser.on(:request) do
  raise("error!")
end

browser.go_to('https://example.com')
sleep
```

### Expected Result

An uncaught exception being raised.

### Actual Result

Nothing

## Version Information

* ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-linux]
* ferrum (0.13)

**Comment by route** [comment]
I believe it's https://github.com/ruby-concurrency/concurrent-ruby/issues/634 but I never had time to work on it.
