### ISSUE TITLE
Doesn't work on ruby 3.2

### ISSUE THREAD

**Issue by mcolyer** [rubycdp/ferrum#408]
It looks like the supported version is >= 2.6.0 but it doesn't seem to work on 3.2.2.

It looks like [Pathname](https://ruby-doc.org/core-3.2.0/Pathname.html) was removed in 3.2.0 ([src](https://github.com/rubycdp/ferrum/blob/7ae00e7ce557c765f9dfcd75b5875cdc1cc186dd/lib/ferrum/page.rb#L373)). Not sure if there are other changes or not.

**Comment by ttilberg** [comment]
Hey Matt, I use Ferrum with Ruby 3.2.2, so you should be good. It looks like you're using a small code path that does require `Pathname` to be present. Pathname comes from a default gem. It requires a `require`. It should be an easy fix in the gem, but in the meantime, try adding a `require 'pathname'` to your script before launching Ferrum.
