### ISSUE TITLE
Saving via browser.mhtml and via cmd+S differs a lot on Youtube

### ISSUE THREAD

**Issue by Nakilon** [rubycdp/ferrum#412]
![image](https://github.com/rubycdp/ferrum/assets/2870363/c81a6b7b-3b4c-400b-b32f-892c50714ab3)
![image](https://github.com/rubycdp/ferrum/assets/2870363/ca9aa1c4-7250-4c60-87e1-3899d9c5ec66)

**Comment by Nakilon** [comment]
nevermind, sry, I need to stop confusing the files to figure my issue out

**Comment by Nakilon** [comment]
Just realised ferrum saw the new youtube design yet in 2023 _Oo

**Comment by route** [comment]
Must be a/b testing then ;)
