### ISSUE TITLE
Remove `disable-gpu`default flag for Apple Silicon

### ISSUE THREAD

**Issue by thibaudgg** [rubycdp/ferrum#421]
The [`disable-gpu` is part of the default Chrome options](https://github.com/rubycdp/ferrum/blob/main/lib/ferrum/browser/options/chrome.rb#L9) but it is causing issues with webpages using WebGL on Apple Silicon machine.

I was able to make it work by removing the `disable-gpu` flag and adding [the `--use-angle=metal` flag](https://github.com/google/angle) via this small monkey-patch:

``` ruby
# Enable GPU (with Metal) for Chrome on Apple Silicon
if Gem::Platform.local.cpu == "arm64" && Gem::Platform.local.os == "darwin"
  chrome_class = Ferrum::Browser::Options::Chrome
  default_options = chrome_class::DEFAULT_OPTIONS.dup

  default_options.delete('disable-gpu')
  default_options['use-angle'] = 'metal'

  chrome_class.send(:remove_const, 'DEFAULT_OPTIONS')
  chrome_class::DEFAULT_OPTIONS = default_options.freeze
end
```

Do you think this should be set by default for Apple Silicon, or at least stop adding the `disable-gpu` flag on this platform?
I'm happy to provide a PR if needed.

**Comment by route** [comment]
From https://developer.chrome.com/blog/headless-chrome

Do I need the --disable-gpu flag?

Only on Windows. Other platforms no longer require it. The --disable-gpu flag is a temporary work around for a few bugs. You won't need this flag in future versions of Chrome. See [crbug.com/737678](https://bugs.chromium.org/p/chromium/issues/detail?id=737678) for more information.


So you are right, we need to add some conditionals for windows and mac most likely. Mind sending a PR?

**Comment by thibaudgg** [comment]
@route sure things, just created a PR for it: https://github.com/rubycdp/ferrum/pull/436

**Comment by route** [comment]
Thanks!
