### ISSUE TITLE
css selector fails sometimes with Node Not Found error

### ISSUE THREAD

**Issue by Valve** [rubycdp/ferrum#43]
If I try this `browser.css("a[href]")` on a very heavy page, it fails sometimes with this Node Not Found error.

Pages to try this on:

qq.com
aliexpress.com

etc

**Comment by route** [comment]
Cannot reproduce it on given sites, I'm afraid it's due to the DOM being changed while accessing it, so probably `browser.network.wait_for_idle` should help to solve this.
