### ISSUE TITLE
Permission denied when using Firefox

### ISSUE THREAD

**Issue by dpaluy** [rubycdp/ferrum#440]
While trying to use Firefox on Mac M1 (ARM)

`browser = Ferrum::Browser.new browser_name: :firefox`

I'm getting an error:
`Permission denied - /Applications/Firefox.app/Contents/MacOS (Errno::EACCES)` on this [step](https://github.com/rubycdp/ferrum/blob/main/lib/ferrum/browser/process.rb#L99)

I'm getting the same error with Brave.

However, the chrome works correctly.

What's the correct way to resolve this issue?

Thank you!

**Comment by route** [comment]
Firefox is not supported for now.
