### ISSUE TITLE
I am getting syntax error after installing ferrum. Am i missing something here

### ISSUE THREAD

**Issue by NabinOjha** [rubycdp/ferrum#449]
![Screenshot from 2024-03-01 16-46-06](https://github.com/rubycdp/ferrum/assets/62282126/dce32d22-8d23-41b3-87e4-8201dfa58ef5)

**Comment by route** [comment]
What ruby version are you on?

**Comment by NabinOjha** [comment]
Thanks for replying. What if I wanted to use 2.7.2? Isn't there any version compatible with ruby 2.7.2

**Comment by route** [comment]
0.14 should be compatible but I’ll check

**Comment by NabinOjha** [comment]
Yes it is compatible.Thanks
