### ISSUE TITLE
0.15 version does not contain exists? for Ferrum::Node

### ISSUE THREAD

**Issue by umairabid** [rubycdp/ferrum#462]
It seems `0.15` is the latest version however its interface does not match with docs on `main` branch. 

The PR for `exists?` function seems to be merged in April however `0.15` version was released in Feb of this year. This results into `NoMethod` error when the gem is installed through bundler as per the instructions. I had to install the gem directly from the branch to fix it.

**Comment by route** [comment]
Readme docs are for unreleased main branch
If you want docs for given version https://github.com/rubycdp/ferrum/tree/v0.15
