### ISSUE TITLE
Allow Ferrum to use default (non incognito) context

### ISSUE THREAD

**Issue by Pugio** [rubycdp/ferrum#47]
I'd like my browser state/session to be preserved between uses of my script.

Currently, Ferrum places all commands inside a BrowserContext, which acts like an Incognito session and doesn't load stored cookies.

I would like to use the browser's default session (which isn't inside a context), and take advantage of the `--user-data-dir` flag to be able to persist state across sessions. This would require modifying how Ferrum uses and creates contexts to allow for non-browserContext requests. I am happy to do this, and submit a PR, but would like some author feedback (if possible) about whether such an option is in line with the project's vision before I start working on code for this.

**Comment by route** [comment]
Absolutely, go ahead! I just didn’t need it thus it was easy not to implement rather than implement. I think it will be as easy as provide a sit and just don’t remove anything from it when quitting.

**Comment by route** [comment]
I think the default context that Chrome creates has a lot of limitations like inability to create pages inside it and so on. If you come up with something useful please open a PR but due to inactivity I'm going to close this issue.

**Comment by yann120** [comment]
Hi,
Is there an other way to persist state between sessions like we can do with Selenium ?
I came to Ferrum to be able to catch network requests, but I need also to persist the session.
Exemple, i'm logged in on a website, I want to be still logged when re-launching the script
Thanks 🙏🏻

**Comment by route** [comment]
@yann120 http is stateless protocol. The state is determined by headers sent from/to web server. If you want to login on the website, close browser and then open it and be logged in, you need to store your cookies somewhere, and next time before telling a browser to visit url, load those cookies.

**Comment by yann120** [comment]
> @yann120 http is stateless protocol. The state is determined by headers sent from/to web server. If you want to login on the website, close browser and then open it and be logged in, you need to store your cookies somewhere, and next time before telling a browser to visit url, load those cookies.
> 
> You open the page and login:
> 
> ```ruby
> browser = Ferrum::Browser.new(headless: false)
> page = browser.create_page
> page.go "https://auth.udacity.com/sign-in?next=https%3A%2F%2Flearn.udacity.com%2F"
> page.network.wait_for_idle
> 
> page.at_xpath("//*[@id='email']").focus
> page.keyboard.type(email)
> page.at_xpath("//*[@id='revealable-password']").focus
> page.keyboard.type(password)
> button = page.at_xpath("//button[@type='button'][./span[.='Sign in']]")
> button.focus.click
> 
> page.network.wait_for_idle
> 
> File.open(path, "w") do |file|
>   file.write(page.cookies.map(&:to_h).to_yaml)
> end
> ```
> 
> Then next time you load all the cookies before opening the page:
> 
> ```ruby
> browser = Ferrum::Browser.new(headless: false)
> page = browser.create_page
> 
> cookies = YAML.load_file(path)
> cookies.each { |c| page.cookies.set(c) }
> page.go "https://learn.udacity.com"
> ```
> 
> [99cfa84](https://github.com/rubycdp/ferrum/commit/99cfa84c56e55bb373da48935d08d5a13df1ad27)

Thanks, I ended up using your solution and it work :)
