### ISSUE TITLE
Random startup failures when running tests with GitHub Actions

### ISSUE THREAD

**Issue by postmodern** [rubycdp/ferrum#489]
I started noticing random exceptions when tests attempted to initialize a `Ferrum::Browser` instance.

```
     Ferrum::ProcessTimeoutError:
2172
       Browser did not produce websocket url within 10 seconds, try to increase `:process_timeout`. See https://github.com/rubycdp/ferrum#customization
2173
     # ./vendor/bundle/ruby/3.2.0/gems/ferrum-0.15/lib/ferrum/browser/process.rb:172:in `parse_ws_url'
2174
     # ./vendor/bundle/ruby/3.2.0/gems/ferrum-0.15/lib/ferrum/browser/process.rb:106:in `start'
2175
     # ./vendor/bundle/ruby/3.2.0/gems/ferrum-0.15/lib/ferrum/browser.rb:247:in `start'
2176
     # ./vendor/bundle/ruby/3.2.0/gems/ferrum-0.15/lib/ferrum/browser.rb:132:in `initialize'
2177
     # ./vendor/bundle/ruby/3.2.0/gems/ronin-web-browser-0.1.0/lib/ronin/web/browser/agent.rb:85:in `initialize'
2178
     # ./vendor/bundle/ruby/3.2.0/gems/ronin-web-browser-0.1.0/lib/ronin/web/browser.rb:127:in `new'
2179
     # ./vendor/bundle/ruby/3.2.0/gems/ronin-web-browser-0.1.0/lib/ronin/web/browser.rb:127:in `new'
2180
     # ./lib/ronin/recon/builtin/web/screenshot.rb:71:in `initialize'
2181
     # ./spec/builtin/web/screenshot_spec.rb:9:in `new'
2182
     # ./spec/builtin/web/screenshot_spec.rb:9:in `block (2 levels) in <top (required)>'
2183
     # ./spec/builtin/web/screenshot_spec.rb:25:in `block (3 levels) in <top (required)>'
2184
     # ./vendor/bundle/ruby/3.2.0/gems/webmock-3.23.1/lib/webmock/rspec.rb:39:in `block (2 levels) in <top (required)>'
```

Sometimes this occurs under Ruby 3.2 or 3.3. I assume this is a known issue?

**Comment by route** [comment]
Nope, are you sure it's not a memory issue? Because all I've seen were memory issues due to which Chrome couldn't not be started.

**Comment by crohr** [comment]
@postmodern I concur with @route, most likely a memory issue. We've hit the same kind of errors at our place, and bumping the RAM helped fix the issue. It might be that ferrum needs (leaks?) more memory than what we used before for testing. This was on a 32CPU/64GB machine with 32 parallel tests, now bumped to 32CPU/128GB machine.

**Comment by postmodern** [comment]
OK, will add a `skip` to the test when GitHub Actions is detected.

**Comment by route** [comment]
@crohr having access to the machine you could prove it right or wrong for ferrum leaks, but ferrum itself is not that much memory hungry, maybe leaking chrome instances that people forget to close?
