### ISSUE TITLE
Any plans to allow passing in HTML instead of a URL?

### ISSUE THREAD

**Issue by reefdog** [rubycdp/ferrum#52]
Hi folks, this is amazing and we hope to be able to collapse our current Grover/Puppeteer/Rails stack to just Ferrum/Rails in the future for screenshot generation of some views.

However, we rely on being able to pass in our views as rendered HTML strings rather than as a URL to fetch. (I think Grover uses [Puppeteer's `setContent()`](https://github.com/puppeteer/puppeteer/blob/master/docs/api.md#pagesetcontenthtml-options) for this.)

Are there plans for Ferrum to support this in the future?

**Comment by route** [comment]
That was actually easy https://github.com/route/ferrum/commit/13ab43d4983d5763f0f7dd0a647289d3561778a6#diff-593bb59ec2e71055f0e04ace86070028R239-R243 but I'll leave this issue open because I need to revisit frames documentation.

**Comment by reefdog** [comment]
That is awesome! (And apologies for the long delay in responding saying so.) Thank you @route! We'll start playing with this.

**Comment by route** [comment]
Added Frame docs to README

**Comment by dtgay** [comment]
Looks like this functionality wasn't merged in. Is there another way to render an HTML+JS blob, for example a Rails template with `ActionController::Base.new#render_to_string`?

**Comment by route** [comment]
What do you mean wasn’t merged?

**Comment by barrywoolgar** [comment]
@route Having just momentarily confused myself with the README too, maybe they meant the docs weren't updated to include an explicit reference to `set_content`? I can see you can do `frame.content = "..."` whereas the linked commit above refers to `set_content`.

We use it like this when rendering HTML for PDF generation, for example:

`browser.main_frame.set_content(pdf_html)`

Not knocking, it all works great for me, I just hate to see a question go unanswered :)
