### ISSUE TITLE
Can this gem be used in a production environment in heroku?

### ISSUE THREAD

**Issue by camiloandresoa99** [rubycdp/ferrum#53]
I would like to know if this gem can be used in production and that the environment is heroku.
If the answer is yes, I would like to know what is needed to set it up

**Comment by coffeejunk** [comment]
Yep this is possible, all you need to do is add the [google-chrome buildpack](https://github.com/heroku/heroku-buildpack-google-chrome), i.e. run `heroku buildpacks:add heroku/google-chrome` and you're good to go.
You can find an arguably terrible example here: https://github.com/coffeejunk/ferrum_heroku

**Comment by camiloandresoa99** [comment]
Friend, the command would be as follows:
`heroku buildpacks:add heroku/google-chrome -a app-name`
???

**Comment by coffeejunk** [comment]
@camiloandresoa99 yep that looks right

**Comment by route** [comment]
It is production ready, you can use it anywhere the only requirement is Chrome, install it and you are done. I personally use it on DO so I haven't tried installing it on heroku. This issue is not related to Ferrum, closing it.
