### ISSUE TITLE
Is there a way to fetch the Javascript console?

### ISSUE THREAD

**Issue by jmettraux** [rubycdp/ferrum#55]
I've tried to setup a `logger:` option when initializing the `Ferrum::Browser` but my `console.log("xyz");` don't make it there.

Is there a way to fetch the Javascript console?

Thanks for the excellent gem.

**Comment by route** [comment]
@jmettraux there's logger option but once you turn it on it will also show cdp protocol as discussed here https://github.com/rubycdp/cuprite/issues/110#issuecomment-584557319

**Comment by jmettraux** [comment]
OK, thanks! I'll dig the logger further.

**Comment by route** [comment]
You are welcome! I'll split logger and cdp soon when I have time, likely closer to the weekend!

**Comment by jmettraux** [comment]
I went with something that can be summarized as:


```ruby
module FerrumHelpers

  class Logger

    def puts(l)

      a = l.strip.split(' ', 3)
      a[2] = JSON.parse(a[2])
      pp a if %w[ Runtime.exceptionThrown Log.entryAdded ].include?(a[2]['method'])
    end
  end

  def browser(opts={})

    opts[:logger] = FerrumHelpers::Logger.new

    Ferrum::Browser.new(opts)
  end

  # ...
end
```

Thanks again!
