### ISSUE TITLE
how to pass Basic Auth when opening a page

### ISSUE THREAD

**Issue by aashish-medici** [rubycdp/ferrum#57]
I Know with puppeteer you can simply pass basic auth by:

 `page.authenticate({'username':'YOUR_BASIC_AUTH_USERNAME', 'password': 'YOUR_BASIC_AUTH_PASSWORD'});`

is there a way to do it with Ferrum ?

**Comment by coffeejunk** [comment]
@aashish-medici https://github.com/rubycdp/ferrum#authorizeoptions
