### ISSUE TITLE
Pick option in select

### ISSUE THREAD

**Issue by sujayvadlakonda** [rubycdp/ferrum#58]
I can't figure out a way to pick an option item in a select. 

Example HTML: 
`<select id="cars" name="cars">
    <option value="volvo">Volvo</option>
    <option value="saab">Saab</option>
    <option value="fiat">Fiat</option>
    <option value="audi">Audi</option>
</select>`

Clicking on the select opens the drop-down list. Using tap { browser.keyboard.type(:Down) } did not work. Option cannot be clicked on, because of being unable to calculate quads.  I could be missing something obvious, and any help would be appreciated.

**Comment by route** [comment]
@sujayvadlakonda you are right there's no such method currently because Chrome CDP doesn't provide it, but it can be emulated with JS like puppeteer did https://github.com/puppeteer/puppeteer/blob/master/lib/JSHandle.js#L290

I'll start working on it.

**Comment by sujayvadlakonda** [comment]
I looked through the JS code that you linked, but I still don't completely get how JS emulation can be used to select an option.

**Comment by Mifrill** [comment]
Hello, @sujayvadlakonda try the solution which [described here](https://stackoverflow.com/questions/45864516/how-to-select-an-option-from-dropdown-select):
```Javascript
// use page.select
await page.select('select[name="choose1"]', 'val2');

// use elementHandle.type
const selectElem = await page.$('select[name="choose1"]');
await selectElem.type('Value 2');
```
in our case it's working by `type` method with `Enter` mode:

```Ruby
it "picks option in select" do
 browser.goto("/ferrum/form")
 input = browser.at_xpath("//*[@id='form_title']")
 expect(input.value).to eq "Mrs"
 input.click
 input.type("Miss", :Enter)
 expect(input.value).to eq "Miss"
end
```

[(it's green spec)](https://github.com/Mifrill/ferrum/commit/d00c1faeefb65b42978d1ba457c116abccc0df95)
![a](https://user-images.githubusercontent.com/23525618/79075322-910ecd00-7d0b-11ea-8131-948bbea2ec72.png)

**Comment by Nakilon** [comment]
This snippet does not work for me. At the step of Enter emulation instead of closing the dropdown it stays open while form does something weird, maybe trying to submit without the option actually being selected since it's still dropped down.

**Comment by zsan** [comment]
Hello @Mifrill 

Sorry for my dumb question, so how do we use it ?

For example i have this HTML's code
```html
<select class="select required hasHelp" 
  tabindex="3" name="applicant[passport_country_code]" 
  id="applicant_passport_country_code" 
  autocomplete="off">
  <option value=""></option>
  <option value="AF">Afghanistan</option>
  <option value="AU">Australia</option>
  <option value="AT">Austria</option>
  <option value="AZ">Azerbaijan</option>
</select>
```

And i tried with

```
browser.at_xpath("//select[@id='applicant_passport_country_code']").select("AU")
```
or
```
browser.at_xpath("//select[@id='applicant_passport_country_code']").select("Australia")
```

and nothing happen, did i miss something ?

**Comment by Mifrill** [comment]
Hi @zsan, there are 2 things here:
1. the `option` with empty text/value picked always (this is a bug I will address in the dedicated issue later) thanks for the catch!
So, try to drop this option if possible:
```diff
<select class="select required hasHelp"
        tabindex="3" name="applicant[passport_country_code]"
        id="applicant_passport_country_code"
        autocomplete="off">
- <option value=""></option>
  <option value="AF">Afghanistan</option>
  <option value="AU">Australia</option>
  <option value="AT">Austria</option>
  <option value="AZ">Azerbaijan</option>
</select>
```
2. need to pick by value instead of text
```ruby
browser.at_xpath("//select[@id='applicant_passport_country_code']").select("AU")
```

**Comment by Mifrill** [comment]
Hey, @zsan check the updated master, bug with "always pick empty value" should be fixed now.
By the way, now we can use any attribute to pick the option, for example, `text`:
```ruby
browser.at_xpath("//select[@id='applicant_passport_country_code']").select("Australia", by: :text)
```

**Comment by zsan** [comment]
@Mifrill 

Wow It's working perfectly, awesome, thank you :)
