### ISSUE TITLE
browser.current_title doesn't work

### ISSUE THREAD

**Issue by sujayvadlakonda** [rubycdp/ferrum#60]
README says browser should have a method called 'current_title'

<img width="1425" alt="Screen Shot 2020-04-02 at 10 54 52 AM" src="https://user-images.githubusercontent.com/37093385/78270398-64b7ad00-74d0-11ea-8529-9500af2cac58.png">

This says it doesn't work. I did `sudo gem install ferrum` to ensure updates. Got ferrum-0.7.

**Comment by route** [comment]
You are right, it's missed in `Browser` delegate
