### ISSUE TITLE
Dealing with JS alerts

### ISSUE THREAD

**Issue by code-ks** [rubycdp/ferrum#62]
Hello Ferrum Developers,

I'm in the midst of programming the macros for a website that includes JavaScript alerts. Thanks to your software it's been a joy so far engaging with this automation work. I do however face a problem with alerts as of now. It seems that there's no native way of dealing with alerts? I would like to either automatically approve them or have them disabled from the start of chromium. I haven't been able to find a proper solution yet, but I would like to hear whether this could be done with Ferrum.

Thank you!

**Comment by route** [comment]
There's a support for alerts https://github.com/rubycdp/ferrum#dialog
