### ISSUE TITLE
Xvfb support

### ISSUE THREAD

**Issue by sebyx07** [rubycdp/ferrum#65]
Hey, I've got ferrum working with xvfb. Are you interested to have ferrum automatically handle Xvfb opening and choosing a display?

Like when you pass `headless: :xfb`

I could PR on this

**Comment by route** [comment]
Are you using it in headful mode to work with extensions in xvfb?

**Comment by sebyx07** [comment]
Yeah, currently with headless: false.
I was able to pass the DISPLAY=:99 by patching your Process#start method a bit

**Comment by route** [comment]
Sounds good! Maybe someone needs it especially for extensions! Thank you!

**Comment by sebyx07** [comment]
For extensions, I 've run ferrum, without xvfb so I could navigate the browser. Put a binding pry so It waits.

Also before had to configure the `user-data-dir`.

While it inside the debugger, I went to the main window, and configured extension to be available in incognito.

Closed, saved the user-data-dir, then I use it as a base for whenever I need. just cp it to a /tmp dir and set user-data-dir to the tmp dir
