### ISSUE TITLE
Leaking chromium.launcher processes?

### ISSUE THREAD

**Issue by jarthod** [rubycdp/ferrum#68]
I've noticed on my CI server (using `cuprite`) a lot of orphan chomium.launcher process with `sleep 60` as child:
![image](https://user-images.githubusercontent.com/201687/79634864-773b1300-816d-11ea-98f5-1a677aca60dd.png)

It looks like this process is started when specs are running:
![image](https://user-images.githubusercontent.com/201687/79634936-f3355b00-816d-11ea-8250-bd33929bec5b.png)
But then it stays orphan after the spec finishes, this may have nothing to do with ferrum but I didn't notice this with chrome-driver previously so I though I would report this.

I'm using Ubuntu 19.10 with Google Chrome `81.0.4044.113`
These processes do not die after 60 seconds, it seems the launcher process is calling sleep 60 in loop. I can also reproduce the issue on my desktop (Ubuntu 19.10 too)

I use this cuprite config:
```ruby
Capybara.javascript_driver = :cuprite
Capybara.register_driver(:cuprite) do |app|
  Capybara::Cuprite::Driver.new(app, headless: true, js_errors: true, timeout: 10, process_timeout: 10)
end
```

Any idea what could cause that?

**Comment by route** [comment]
@jarthod Hm maybe you can get the content of `chromium.launcher` because I'm not sure what this is. I think this is a wrapper your CI uses as it's the parent of all the browser processes, maybe it's kind of a wrapper CIrcleCI has to add sandbox options to Chrome. At least I would start with. What CI do you use?

**Comment by jarthod** [comment]
It's not related to the CI I'm using as it's a simple Ubuntu 19.10 desktop machine (and it's the same on my desktop). I had a deeper look at what `chromium.launcher` does and it seems like it's specific to the snap package. It looks like they added this "background process" on purpose to notify the user when the version of chrome changes, apparently without thinking about when to stop it -_-

```bash
# Notify users when the snap has been refreshed while running.
# Ref: https://launchpad.net/bugs/1864901
check_current_symlink() {
  CURRENT_SNAP_REVISION=$SNAP_REVISION
  REVISIONS_DIR=$(dirname $SNAP)
  CURRENT_SYMLINK="$REVISIONS_DIR/current"
  while true; do
    NEW_SNAP_REVISION=$(readlink $CURRENT_SYMLINK)
    if [ "$NEW_SNAP_REVISION" != "$CURRENT_SNAP_REVISION" ]; then
      CURRENT_SNAP_REVISION=$NEW_SNAP_REVISION
      notify-send --icon="$SNAP/chromium.png" --app-name="Chromium" \
        "Chromium has been updated." \
        "It needs to be restarted for changes to take effect."
    fi
    sleep 60
  done
}
check_current_symlink &
```
Source: https://bugs.launchpad.net/ubuntu/+source/chromium-browser/+bug/1864901

**Comment by jarthod** [comment]
I'll report the problem to them then, sorry for the issue but at least if other people find themselves in the same situation they may find the answer here ;)

**Comment by route** [comment]
No problem all good I’m glad you figured it out!
