### ISSUE TITLE
Is there any way I could use a proxy?

### ISSUE THREAD

**Issue by simoniong** [rubycdp/ferrum#72]
Hi, thanks for the great tools, seems all good, and I am looking around if I could pass in a proxy setting in the middle of my local machine to target website. Is there any options for me to do that now?

**Comment by coffeejunk** [comment]
You can do this by passing`proxy-server` in the `browser_options` when you instantiate the browser:

```ruby
proxied_browser = Ferrum::Browser.new(
  browser_options: { "proxy-server" => "localhost:3128" }
)
```

**Comment by route** [comment]
Though keep in mind that you can't change proxy settings while using the browser, this is Chrome's limitation, but the workaround would be to quit this and create new one.

**Comment by 9mm** [comment]
@route how would one add in username/password into it?

**Comment by route** [comment]
@9mm https://github.com/rubycdp/ferrum#authorizeoptions

**Comment by 9mm** [comment]
@route sorry I mean proxy username/password. I looked up `proxy-server` options and its not allowed. I set up a proxy with tinyproxy and did it that way

**Comment by route** [comment]
> @route sorry I mean proxy username/password. I looked up `proxy-server` options and its not allowed. I set up a proxy with tinyproxy and did it that way

Yea I know, it works for either server or proxy. Take a look closer at arguments

**Comment by zedtux** [comment]
Apparently, from my checks from the source code, it appear that the proxy option is not passed to the remote browser whenever there's an `:url` option.

Is there any good reason for that ? Would you consider allowing to pass the proxy config to the remote browser if it is possible ?
