### ISSUE TITLE
Feature request: unsubscribe from notifications

### ISSUE THREAD

**Issue by betelgeuse** [rubycdp/ferrum#84]
https://github.com/rubycdp/ferrum/blob/e02b2399dacdcca36f0347832d0580eaee1ee0ed/lib/ferrum/browser/subscriber.rb#L20

It would be useful to be able to unsubscribe from these. What do you think about using ActiveSupport::Notifications to implement event handling?

**Comment by route** [comment]
Hi Petteri, unsubscription sounds good! Though activesupport is a huge dependency, it's better implement it ourselves

**Comment by betelgeuse** [comment]
It doesn't really add memory footprint if we only use the notifications

```
irb(main):001:0> require 'get_process_mem'
=> true
irb(main):002:0> GetProcessMem.new
=> #<GetProcessMem:0x00000190 @mb=25.609375 @gb=0.0250091552734375 @kb=26224.0 @bytes=26853376>
irb(main):003:0> require 'active_support/notifications'
=> true
irb(main):004:0> ActiveSupport::Notifications.subscribe('foo.example') do |*args| p 'here' end
=> #<ActiveSupport::Notifications::Fanout::Subscribers::Timed:0x00007f824f062768 @pattern="foo.example", @delegate=#<Proc:0x00007f824f0627e0 (irb):4>, @can_publish=false>
irb(main):005:0> ActiveSupport::Notifications.instrument('foo.example') do true end
"here"
=> true
irb(main):009:0>  GetProcessMem.new
=> #<GetProcessMem:0x000001e0 @mb=27.3984375 @gb=0.02675628662109375 @kb=28056.0 @bytes=28729344>
``

**Comment by betelgeuse** [comment]
Given that you need chrome running to use ferrum, I don't think a bit of memory for active support is that relevant. Of course, up to you.

**Comment by route** [comment]
I still think that AS is a huge dependency and prefer to keep the stack short, especially when a feature can be implemented relatively easy

**Comment by betelgeuse** [comment]
Would you then also prefer to reimplement all the other features that AS would provide?

**Comment by route** [comment]
I don't need all features, but you can go ahead and make your fork
