### ISSUE TITLE
NoMethodError (undefined method `compact' for "(cyclic structure)":String in Browser#css

### ISSUE THREAD

**Issue by PandaWhisperer** [rubycdp/ferrum#85]
## Problem

Calling `Browser#css` with seemingly _any_ parameter fails with the following error:

    NoMethodError (undefined method `compact' for "(cyclic structure)":String)

## Steps to reproduce

```ruby
browser = Ferrum::Browser.new
browser.goto("https://www.google.com")
# this works:
browser.at_css('input') # => Ferrum::Node
# this doesn't:
browser.css('input') # => NoMethodError (undefined method `compact' for "(cyclic structure)":String)
# but this does:
browser.xpath('//input') # => [Ferrum::Node]
```

## Expected behavior

I was expecting the method to return an Array of `Ferrum::Node` objects containing all the nodes matched by the selector, similar to how `Browser#xpath` behaves.

**Comment by ttilberg** [comment]
Related: #73 #13 

@PandaWhisperer can you try with master branch? It was mentioned in #73 that a fix was added, but it looks like a new release hasn't been cut.

**Comment by ttilberg** [comment]
See this note: https://github.com/rubycdp/ferrum/issues/73#issuecomment-620401681

**Comment by PandaWhisperer** [comment]
@ttilberg as far as I can tell I AM using the master branch. 

I did some digging and I found the method implementation [here](https://github.com/rubycdp/ferrum/blob/96456ea541ca0743b4ad58e940f94312e9bef854/lib/ferrum/frame/dom.rb#L68-L77)

```ruby
      def css(selector, within: nil)
        code = <<~JS
          let selector = arguments[0];
          let within = arguments[1] || document;
          let results = within.querySelectorAll(selector);
          arguments[2](results);
        JS


        evaluate_async(code, @page.timeout, selector, within)
      end
```

I copied the JS code definition and ran the same `browser.evaluate_async` call in my local console. Still getting the same error.

HOWEVER, while futzing around with this I also found the solution: `document.querySelector()` returns a `NodeList`, not an `Array` (as the XPath version does). So, I changed the JS code to turn the `NodeList` into an Array, like so:

```javascript
let selector = arguments[0];
let within = arguments[1] || document;
let results = [].slice.apply(within.querySelectorAll(selector));
arguments[2](results);
```
Running this code using `browser.evaluate_async` worked, and returned the expected result.

**Comment by PandaWhisperer** [comment]
@ttilberg does this make sense?

I've been trying to come up with a test case for this scenario, but so far I have failed. I see the `Browser#css` method has tests and works for the cases you have for it. So far I haven't been able to figure out what's different between your test cases and "in the wild" pages.

**Comment by ttilberg** [comment]
I think you mean to tag @route -- I'm just a random onlooker who keeps close tabs on the project ;)

**Comment by route** [comment]
Sorry guys I had a branch when you tagged me but then life came in and walked me away lol. I like your soultion @PandaWhisperer and I'm gonna intro one more thing, let me rebase and continue working in my branch.

**Comment by route** [comment]
I merged one more thing regarding cyclic structure but @PandaWhisperer I think this https://github.com/rubycdp/cuprite/commit/62e2a271533eb32c756aae9ecc47975f1a39dc3c should have fixed your issue any chance you were using old branches? Please upgrade ferrum and let me know if it's still an issue for you. Thanks!

PS: Tried your scenario on master, everything works now.
