### ISSUE TITLE
Set value for non-focusable input

### ISSUE THREAD

**Issue by wojtha** [rubycdp/ferrum#90]
Is there a way how to fill hidden input field? Eg. a TEXTAREA with `style="display: none;"`.

When I do this:

```
page.at_css('#hidden-field').focus.type('foobar')
```

I get `Ferrum::BrowserError: Element is not focusable`

Currenly this is working for me, but some native way of setting hidden values would be nice.

```
page.execute("document.getElementById('hidden-field').value = 'foobar'")
```

Is there a better way?

**Comment by Mifrill** [comment]
Hey @wojtha, thanks for reaching out!
So, the `focus`-exception on non-visible elements looks fine, I guess.

We can probably use this solution:
```
input = page.at_css('#hidden-field')
input.set_attribute("foobar", name: "value") if input.display_none?

```
Here is draft PR: https://github.com/rubycdp/ferrum/pull/143

**Comment by route** [comment]
Added `focuable?` so you can check before trying to focus
